name: Secret Check
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CLAUDE_API_KEY:  ${{ secrets.CLAUDE_API_KEY  != '' }}"
          echo "CODEX_API_KEY :  ${{ secrets.CODEX_API_KEY   != '' }}"
          echo "GEMINI_API_KEY:  ${{ secrets.GEMINI_API_KEY  != '' }}"
          echo "MANAS_ENDPOINT:  ${{ secrets.MANAS_ENDPOINT  != '' }}"
          echo "MANAS_TOKEN   :  ${{ secrets.MANAS_TOKEN     != '' }}"
          echo "SHEETS_WEBHOOK:  ${{ secrets.SHEETS_WEBHOOK  != '' }}"
